# Mod Properties
mod_id=thermal_integration
mod_name=Thermal Integration
mod_version=11.0.2

# Platform Properties
java_version=17
mc_version=1.20.1
neo_version=20.4.237

# Dependency Properties
cofh_core_version=11.0.2
cofh_core_max_version=11.1.0

thermal_core_version=11.0.4
thermal_core_max_version=11.1.0

# Publishing Properties

# Options: alpha, beta, release
release_type=release