modLoader = "javafml"
loaderVersion = "[${forge_major_version},)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_integration"
version = "${file.jarVersion}"
displayName = "Thermal Integration"
updateJSONURL = "https://raw.github.com/cofh/version/main/thermal/update_integration.json"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_integration.png"
itemIcon = "thermal:steel_gear"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Integrating Thermal with the wider modded ecosystem!

Contains Thermal machine recipes and compatibility for many different mods.
'''
[[dependencies.thermal_integration]]
modId = "minecraft"
mandatory = true
versionRange = "1.20.1"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_integration]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_integration]]
modId = "cofh_core"
mandatory = true
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_integration]]
modId = "thermal"
mandatory = true
versionRange = "${thermal_core_version_range}"
ordering = "AFTER"
side = "BOTH"